# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(370, 143)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Login)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 20, 291, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.authorizationLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.authorizationLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.authorizationLayout.setContentsMargins(0, 0, 0, 0)
        self.authorizationLayout.setSpacing(7)
        self.authorizationLayout.setObjectName("authorizationLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(False)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.login = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.login.setMouseTracking(False)
        self.login.setObjectName("login")
        self.verticalLayout_3.addWidget(self.login)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.sign_up = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sign_up.setObjectName("sign_up")
        self.horizontalLayout.addWidget(self.sign_up)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.authorizationLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Введите Ваш логин"))
        self.login_button.setText(_translate("Login", "Войти"))
        self.sign_up.setText(_translate("Login", "Создать пользователя"))
