# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(370, 267)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Registration)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 20, 291, 190))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.authorizationLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.authorizationLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.authorizationLayout.setContentsMargins(0, 0, 0, 0)
        self.authorizationLayout.setSpacing(7)
        self.authorizationLayout.setObjectName("authorizationLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setMouseTracking(False)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.login = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.login.setMouseTracking(False)
        self.login.setObjectName("login")
        self.verticalLayout_3.addWidget(self.login)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(False)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.input_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.input_name.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.input_name.setMouseTracking(False)
        self.input_name.setObjectName("input_name")
        self.verticalLayout_3.addWidget(self.input_name)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setMouseTracking(False)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.input_surname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.input_surname.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.input_surname.setMouseTracking(False)
        self.input_surname.setObjectName("input_surname")
        self.verticalLayout_3.addWidget(self.input_surname)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sign_up = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sign_up.setObjectName("sign_up")
        self.horizontalLayout.addWidget(self.sign_up)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.authorizationLayout.addLayout(self.verticalLayout_3)
        self.return_back = QtWidgets.QPushButton(Registration)
        self.return_back.setGeometry(QtCore.QRect(110, 230, 135, 28))
        self.return_back.setObjectName("return_back")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Registration"))
        self.label_3.setText(_translate("Registration", "Придумайте логин"))
        self.label.setText(_translate("Registration", "Введите Ваше имя"))
        self.label_2.setText(_translate("Registration", "Введите Вашу фамилию"))
        self.sign_up.setText(_translate("Registration", "Создать пользователя"))
        self.return_back.setText(_translate("Registration", "Вернуться"))
